spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blearning_users?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true

  rabbitmq:
    host: localhost
    port: 3032
    username: guest
    password: guest
